# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Coordinator
                                 A QGIS plugin
 Plugin to handle coordinate tasks better
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-05-04
        copyright            : (C) 2019 by Jonas K�pper
        email                : qgis@ag99.de
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""
from qgis.core import QgsMessageLog

# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Coordinator class from file Coordinator.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .coordinator import Coordinator
    #QgsMessageLog.logMessage("!!", "Coordinator")
    return Coordinator(iface)